name: CI (Dingux)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container: ghcr.io/irixxxx/toolchain-dingux
    steps:
    - uses: myci-actions/checkout@8
    - name: build
      run: |
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        CROSS_COMPILE=mipsel-linux- ./configure --platform=dingux
        CROSS_COMPILE=mipsel-linux- make
        mv PicoDrive-dge.zip PicoDrive-dge-$ver.zip
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-dge*.zip

