name: CI (GP2X)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ghcr.io/irixxxx/toolchain-gp2x
    permissions:
      packages: read
    steps:
    - uses: myci-actions/checkout@8
    - name: build
      run: |
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        CROSS_COMPILE=arm-none-eabi- ./configure --platform=gp2x
        make PLATFORM_MP3=0
        make -C platform/gp2x rel VER=$ver
        mv PicoDrive_$ver.zip PicoDrive-gph_$ver.zip
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-gph_*.zip

