name: CI (GP2X)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: build environment
      run: |
        whoami
        docker build -f .github/workflows/Dockerfile-gp2x -t build-gp2x .
    - name: build
      run: |
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        dock="docker run -i -v $PWD:/home/picodrive -w /home/picodrive build-gp2x"
        $dock sh -c "git config --global --add safe.directory /home/picodrive"
        $dock sh -c "CROSS_COMPILE=arm-none-eabi- ./configure --platform=gp2x"
        $dock sh -c "make PLATFORM_MP3=0"
        $dock sh -c "make -C platform/gp2x rel VER=$ver"
        mv PicoDrive_$ver.zip PicoDrive-gph_$ver.zip
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-gph_*.zip

