name: CI (GP2X)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: build environment
      run: |
        whoami
        docker build -f .github/workflows/Dockerfile-gp2x -t build-gp2x .
    - name: build
      run: |
        docker run -it -v "$PWD":"/home/picodrive" build-gp2x /bin/sh -c ' \
		cd /home/picodrive && \
		ver=$(sed s/^[^"]*"//;s/"[^"]*$// platform/common/version.h)-$(git rev-parse --short HEAD) && \
		CROSS_COMPILE=arm-none-eabi- ./configure --platform=gp2x && \
		make PLATFORM_MP3=0 && \
		make -C platform/gp2x rel VER="$rel" && \
		mv "PicoDrive_$rel.zip" "PicoDrive-gph_$rel.zip" \
        '
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-gph_*.zip

