name: CI (Miyoo)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: build environment
      run: |
        whoami
        docker pull miyoocfw/toolchain
    - name: build
      run: |
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        dock="docker run -i -v $PWD:/home/picodrive -w /home/picodrive miyoocfw/toolchain"
        $dock sh -c "git config --global --add safe.directory /home/picodrive"
        $dock sh -c "CROSS_COMPILE=arm-buildroot-linux-musleabi- ./configure --platform=miyoo"
        $dock sh -c "CROSS_COMPILE=arm-buildroot-linux-musleabi- make"
        mv PicoDrive.zip PicoDrive-miyoo-$ver.zip
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-miyoo*.zip

