name: CI (Opendingux)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ghcr.io/irixxxx/toolchain-opendingux
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build
      run: |
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        CROSS_COMPILE=mipsel-linux- ./configure --platform=opendingux
        CROSS_COMPILE=mipsel-linux- make
        mv PicoDrive.opk PicoDrive-opendingux-$ver.opk
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-opendingux*.opk

