name: CI (PSP)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspdev
    steps:
    - name: build environment
      run: |
        apk add git gcc g++ zip
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: build
      run: |
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        CROSS_COMPILE=psp- ./configure --platform=psp
        CROSS_COMPILE=psp- make
        make -C platform/psp rel VER=$ver
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive_psp_*.zip

