name: CI (RetroFW)
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: build environment
      run: |
        whoami
        docker build -f .github/workflows/Dockerfile-retrofw -t build-retrofw .
    - name: build
      run: |
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        dock="docker run -i -v $PWD:/home/picodrive -w /home/picodrive build-retrofw"
        $dock sh -c "git config --global --add safe.directory /home/picodrive"
        $dock sh -c "CROSS_COMPILE=mipsel-RetroFW-linux-uclibc- ./configure --platform=retrofw"
        $dock sh -c "CROSS_COMPILE=mipsel-RetroFW-linux-uclibc- make"
        mv PicoDrive.opk PicoDrive-retrofw-$ver.opk
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build result
        path: PicoDrive-retrofw*.opk

