# build container for GP2X

FROM --platform=linux/386 ubuntu:18.04

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip gcc g++

# toolchain and libraries
#RUN	wget --no-check-certificate "https://web.archive.org/web/http://www.gcw-zero.com/files/opendingux-gcw0-toolchain.2014-08-20.tar.bz2" && \
RUN	wget --no-check-certificate "https://git.libretro.com/libretro-infrastructure/libretro-build-dingux/-/raw/master/toolchain/opendingux-gcw0-toolchain.2014-08-20.tar.bz2" && \
	tar xjCf /opt opendingux-gcw0-toolchain.2014-08-20.tar.bz2

# toolchain definitions
ENV PATH=/opt/gcw0-toolchain/usr/bin:$PATH
ENV TS=/opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot
ENV CFLAGS="--sysroot $TS -I$TS/usr/include/SDL -mabicalls"
ENV LDFLAGS="$CFLAGS -Wl,--dynamic-linker=/lib/ld-uClibc.so.0"
ENV CROSS_COMPILE=mipsel-linux-
