# build container for PSP

FROM --platform=linux/amd64 ghcr.io/pspdev/pspsdk

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apk add zip

# toolchain definitions
ENV CFLAGS="-U_FORTIFY_SOURCE -I/home/include"
ENV LDFLAGS="-L/home/lib"

# additional libraries
RUN	cd /home && mkdir /home/lib /home/include && \
	wget "http://www.zlib.net/zlib-1.3.tar.gz" && tar xzf zlib-1.3.tar.gz && cd zlib-1.3 && \
	CC=psp-gcc CFLAGS="$CFLAGS -Os" ./configure --static --libdir=/home/lib --includedir=/home/include && \
	make AR=psp-ar install
RUN	cd /home && wget --no-check-certificate "https://downloads.sourceforge.net/project/libpng/libpng12/1.2.59/libpng-1.2.59.tar.gz" && \
	tar xzf libpng-1.2.59.tar.gz && cd libpng-1.2.59 && \
	CC=psp-gcc CFLAGS="$CFLAGS -Os" ./configure --host=mips-elf --libdir=/home/lib --includedir=/home/include && \
	make install
